/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrontpageIndexRouteImport } from './routes/frontpage/index'
import { Route as CreateReportIndexRouteImport } from './routes/create-report/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontpageIndexRoute = FrontpageIndexRouteImport.update({
  id: '/frontpage/',
  path: '/frontpage/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReportIndexRoute = CreateReportIndexRouteImport.update({
  id: '/create-report/',
  path: '/create-report/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-report': typeof CreateReportIndexRoute
  '/frontpage': typeof FrontpageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-report': typeof CreateReportIndexRoute
  '/frontpage': typeof FrontpageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-report/': typeof CreateReportIndexRoute
  '/frontpage/': typeof FrontpageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-report' | '/frontpage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-report' | '/frontpage'
  id: '__root__' | '/' | '/create-report/' | '/frontpage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateReportIndexRoute: typeof CreateReportIndexRoute
  FrontpageIndexRoute: typeof FrontpageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontpage/': {
      id: '/frontpage/'
      path: '/frontpage'
      fullPath: '/frontpage'
      preLoaderRoute: typeof FrontpageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-report/': {
      id: '/create-report/'
      path: '/create-report'
      fullPath: '/create-report'
      preLoaderRoute: typeof CreateReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateReportIndexRoute: CreateReportIndexRoute,
  FrontpageIndexRoute: FrontpageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
